---
- hosts: all
  vars:
    user1: aagrawa8
  user: "{{user1}}"

  tasks:
   - name: cloning repo
     sudo: false
     command: git clone https://github.com/amritbhanu/Spark_VCL.git

   - name: create spark dir
     sudo: false
     file: path=/home/{{user1}}/spark state=directory mode=0755

   - name: download spark
     sudo: false
     get_url: url=http://ftp.wayne.edu/apache//spark/spark-1.6.0/spark-1.6.0-bin-hadoop2.6.tgz dest=/home/{{user1}}/spark/

   - name: Unarchive Spark download
     sudo: false
     unarchive: src=/home/{{user1}}/spark/spark-1.6.0-bin-hadoop2.6.tgz dest=/home/{{user1}}/spark copy=no

   - name: Move spark dir to spark_latest
     sudo: false
     command: mv /home/{{user1}}/spark/spark-1.6.0-bin-hadoop2.6 /home/{{user1}}/spark/spark_latest

   - name: download hadoop
     sudo: false
     get_url: url=http://mirrors.sonic.net/apache/hadoop/common/hadoop-2.6.0/hadoop-2.6.0.tar.gz dest=/home/{{user1}}/

   - name: Unarchive hadoop download
     sudo: false
     unarchive: src=/home/{{user1}}/hadoop-2.6.0.tar.gz dest=/home/{{user1}}/ copy=no

   - name: Move spark dir to spark_latest
     sudo: false
     command: mv /home/{{user1}}/hadoop-2.6.0 /home/{{user1}}/hadoop

   - name: Changing ownership
     sudo: false
     command: chown -R {{user1}} /home/{{user1}}/hadoop

   - name: writing to bashrc
     blockinfile: |
        dest=/home/{{user1}}/.bashrc backup=yes
        content="export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
		export HADOOP_INSTALL=/home/aagrawa8/hadoop
		export PATH=$PATH:$HADOOP_INSTALL/bin
		export PATH=$PATH:$HADOOP_INSTALL/sbin
		export HADOOP_MAPRED_HOME=$HADOOP_INSTALL
		export HADOOP_COMMON_HOME=$HADOOP_INSTALL
		export HADOOP_HDFS_HOME=$HADOOP_INSTALL
		export YARN_HOME=$HADOOP_INSTALL
		export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native
		export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib/native""

